import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";
import Head from "next/head";
const Layout = ({ children, title, countCartItems }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " - Vegan Food" : "Vegan Food"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar countCartItems={countCartItems} />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
